ig.module(
	'game.entities.item.electricitem'
)
.requires(
	'game.entities.item.item'
)
.defines(function(){
	
EntityElectricitem = EntityItem.extend({

	size: {x: 16, y: 22},
	offset: {x: 8, y:8},

	energized: false, // Override in weltmeister if this should be energized from the start
	
	// TODO: This is just placeholder for now
	animSheet: new ig.AnimationSheet( 'media/sprites/TheCreature01.png', 32, 32 ),

	name: "",	// auto-generated by the room name (override in weltmeister if more than one per room)

	damage: 1,

	init: function( x, y, settings ) {
		this.parent( x, y, settings );
		
		this.addAnim( 'idle', 0.1, [129] );
		this.addAnim( 'energized', 0.1, [131, 132] );
		this.currentAnim = this.anims.idle.rewind();

		this.name = ig.game.currentLevelName + '.' + this.name;

		
	},

	startUpdate: function() {
		this.parent();

		if (this.energized || ig.game.oneTimeEvents.energized.indexOf(this.name) != -1) {
			this.activate();
		}
	},

	// Get energized from the player
	activate: function() {
		if (!this.energized && ig.game.oneTimeEvents.energized.indexOf(this.name) == -1) {
			ig.game.oneTimeEvents.energized.push(this.name);
		}
		this.energized = true;
		this.currentAnim = this.anims.energized.rewind();
		
	},

	// Energize the player or hurt them
	collected: function( other ) {
		if (this.energized) {
			if (ig.game.playerState.energize) {
				ig.game.player.getEnergized();
			} else {
				other.receiveDamage( this.damage, this );
			}
		} else {
			if (ig.game.playerState.energized) {
				this.activate();
			}
		}
	}
});

});